name: singer_synth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dart_melty_soundfont: ^1.1.14
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.6
  flutter_pcm_sound: ^1.2.2
  music_notes: ^0.18.0
  tonic: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/sf2/
  uses-material-design: true
